//! Identifier newtypes.
//!
//! Every identifier Garrison hands out is a TypeID from the `mti` crate,
//! matching acton-ai's convention: a prefixed, time-sortable, globally unique
//! string like `thread_01h455vb4pex5vsknk084sn02q`. The prefix is the point.
//! A thread identifier that turns up in a log line, an audit entry, or a
//! protocol frame says what it identifies without anyone having to look it up,
//! and a client that sends a conversation ID where a thread ID belongs is
//! rejected at the parse rather than three layers down.
//!
//! The definitions are generated by [`typed_id`] rather than written out
//! longhand. acton-ai writes each of its eight out by hand; at two IDs the
//! duplication is already the more likely place for a mistake to hide, since
//! the only thing that differs between them is a four-character prefix.

use mti::prelude::*;
use serde::{Deserialize, Deserializer, Serialize, Serializer};
use std::fmt;
use std::str::FromStr;

/// Defines a TypeID newtype and its parse error.
///
/// Generates the same surface acton-ai's hand-written IDs expose: `PREFIX`,
/// `new`, `parse`, `inner`, and impls of `Default`, `Display`, `FromStr`,
/// `AsRef<MagicTypeId>`, `Serialize`, and `Deserialize`. Serialization is
/// hand-written rather than derived so the wire form is a plain string, not a
/// one-element tuple.
macro_rules! typed_id {
    (
        $(#[$id_meta:meta])*
        $name:ident,
        $(#[$err_meta:meta])*
        $error:ident,
        $prefix:literal,
        $noun:literal
    ) => {
        $(#[$id_meta])*
        #[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
        pub struct $name(MagicTypeId);

        $(#[$err_meta])*
        #[derive(Debug, Clone, PartialEq, Eq)]
        #[non_exhaustive]
        pub enum $error {
            /// The string is not a well-formed TypeID.
            Parse(String),
            /// The string is a TypeID, but for something else.
            WrongPrefix {
                /// The prefix this type requires.
                expected: &'static str,
                /// The prefix actually found.
                actual: String,
            },
        }

        impl fmt::Display for $error {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
                match self {
                    Self::Parse(e) => write!(f, concat!("invalid ", $noun, " ID: {}"), e),
                    Self::WrongPrefix { expected, actual } => {
                        write!(f, "expected prefix '{expected}', got '{actual}'")
                    }
                }
            }
        }

        impl std::error::Error for $error {}

        impl $name {
            /// The TypeID prefix.
            pub const PREFIX: &'static str = $prefix;

            #[doc = concat!("Creates a new ", $noun, " ID from a fresh UUIDv7, so it sorts by creation time.")]
            #[must_use]
            pub fn new() -> Self {
                Self(Self::PREFIX.create_type_id::<V7>())
            }

            #[doc = concat!("Parses a ", $noun, " ID, checking the prefix.")]
            ///
            /// # Errors
            ///
            /// Returns `Parse` if the string is not a TypeID at all, and
            /// `WrongPrefix` if it is one for a different kind of thing.
            pub fn parse(s: &str) -> Result<Self, $error> {
                let id = MagicTypeId::from_str(s).map_err(|e| $error::Parse(e.to_string()))?;
                let prefix = id.prefix().as_str();
                if prefix != Self::PREFIX {
                    return Err($error::WrongPrefix {
                        expected: Self::PREFIX,
                        actual: prefix.to_string(),
                    });
                }
                Ok(Self(id))
            }

            /// The underlying TypeID.
            #[must_use]
            pub const fn inner(&self) -> &MagicTypeId {
                &self.0
            }
        }

        impl Default for $name {
            fn default() -> Self {
                Self::new()
            }
        }

        impl fmt::Display for $name {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
                write!(f, "{}", self.0)
            }
        }

        impl FromStr for $name {
            type Err = $error;

            fn from_str(s: &str) -> Result<Self, Self::Err> {
                Self::parse(s)
            }
        }

        impl AsRef<MagicTypeId> for $name {
            fn as_ref(&self) -> &MagicTypeId {
                &self.0
            }
        }

        impl Serialize for $name {
            fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
            where
                S: Serializer,
            {
                self.0.to_string().serialize(serializer)
            }
        }

        impl<'de> Deserialize<'de> for $name {
            fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
            where
                D: Deserializer<'de>,
            {
                let s = String::deserialize(deserializer)?;
                Self::parse(&s).map_err(serde::de::Error::custom)
            }
        }
    };
}

typed_id!(
    /// A conversation thread: one ongoing exchange between a client and the agent.
    ///
    /// Distinct from acton-ai's `ConversationId`, which names the prompt-loop
    /// history. A thread owns a conversation; the two are one-to-one today but
    /// a thread also owns turn state, a plan, and a client owner, so conflating
    /// them would mean the protocol's identity changed whenever the prompt
    /// loop's did.
    ThreadId,
    /// Raised when a string is not a valid [`ThreadId`].
    InvalidThreadId,
    "thread",
    "thread"
);

typed_id!(
    /// One connected protocol client — an IDE window, or the `ping` smoke client.
    ///
    /// Threads are owned by the client that created them, so an approval
    /// request goes back to the connection that can actually render a dialog
    /// rather than to whichever client happens to be connected.
    ClientId,
    /// Raised when a string is not a valid [`ClientId`].
    InvalidClientId,
    "client",
    "client"
);

typed_id!(
    /// One turn: a client message and everything the agent does in response.
    ///
    /// Garrison mints this, rather than surfacing acton-ai's `TurnId`, because
    /// acton-ai never tells the caller of `collect()` which turn it started —
    /// the identifier exists only inside the prompt loop and on the broker. A
    /// protocol whose events could not name their own turn until the first
    /// broadcast arrived would be unusable, so the wire uses Garrison's
    /// identity throughout and acton-ai's stays an internal routing detail.
    TurnId,
    /// Raised when a string is not a valid [`TurnId`].
    InvalidTurnId,
    "turn",
    "turn"
);

typed_id!(
    /// One outstanding approval round-trip.
    ///
    /// Minted when a tool call suspends, and quoted back by the client in
    /// `approval.respond`. A separate identifier rather than reusing the tool
    /// call's, because a client may answer out of order and the agent must be
    /// able to say which question it is answering.
    ApprovalId,
    /// Raised when a string is not a valid [`ApprovalId`].
    InvalidApprovalId,
    "appr",
    "approval"
);

typed_id!(
    /// One installation of this daemon on one machine.
    ///
    /// Unlike the four above, this one outlives the process. It is minted once
    /// at enrollment, written to the install record, and read back on every
    /// subsequent start, because the control plane keys a machine's whole
    /// history on it: which grant admitted it, which credentials it has held,
    /// which sessions it ran. A daemon that minted a fresh one each boot would
    /// look like a new machine every morning.
    InstallId,
    /// Raised when a string is not a valid [`InstallId`].
    InvalidInstallId,
    "inst",
    "install"
);

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn each_id_carries_its_own_prefix() {
        assert!(ThreadId::new().to_string().starts_with("thread_"));
        assert!(ClientId::new().to_string().starts_with("client_"));
        assert!(ApprovalId::new().to_string().starts_with("appr_"));
    }

    #[test]
    fn an_id_survives_a_string_round_trip() {
        let id = ThreadId::new();
        let parsed = ThreadId::parse(&id.to_string()).expect("round-trips");
        assert_eq!(id, parsed);
    }

    #[test]
    fn a_thread_id_refuses_an_id_for_something_else() {
        // The whole reason for prefixes: a client that sends a client ID where
        // a thread ID belongs is caught here, not by a lookup miss later that
        // looks identical to "that thread was closed".
        let client = ClientId::new().to_string();
        let error = ThreadId::parse(&client).expect_err("wrong prefix is refused");
        assert_eq!(
            error,
            InvalidThreadId::WrongPrefix {
                expected: "thread",
                actual: "client".to_string(),
            }
        );
    }

    #[test]
    fn nonsense_is_refused_as_unparseable_rather_than_as_a_prefix_mismatch() {
        let error = ThreadId::parse("not-an-id").expect_err("garbage is refused");
        assert!(matches!(error, InvalidThreadId::Parse(_)), "{error:?}");
    }

    #[test]
    fn an_id_serializes_as_a_bare_string() {
        // The wire form has to be a string: a tuple-struct encoding would put
        // `["thread_..."]` on the wire and every client would have to unwrap it.
        let id = ThreadId::new();
        let json = serde_json::to_string(&id).expect("serializes");
        assert_eq!(json, format!("\"{id}\""));

        let back: ThreadId = serde_json::from_str(&json).expect("deserializes");
        assert_eq!(id, back);
    }

    #[test]
    fn deserializing_a_wrongly_prefixed_id_fails_rather_than_coercing() {
        let json = format!("\"{}\"", ClientId::new());
        let result: Result<ThreadId, _> = serde_json::from_str(&json);
        assert!(
            result.is_err(),
            "a client ID must not deserialize as a thread ID"
        );
    }

    #[test]
    fn ids_sort_by_creation_time() {
        // UUIDv7 backing means a sorted list of IDs is a chronological one,
        // which is what makes `thread.list` orderable without a timestamp.
        let first = ThreadId::new();
        let second = ThreadId::new();
        assert!(first < second, "{first} should sort before {second}");
    }
}
